// The hardcoded 'projects' array and the 'renderProjects' function have been REMOVED.
// The HTML is now generated by the C# backend.

// This script now only handles the CLIENT-SIDE interactivity (filtering and navigation).

function initializeCarousel() {
    const track = document.getElementById('carouselTrack');
    if (!track) return; // Safety check

    // --- FILTERING LOGIC ---
    document.querySelectorAll('.filter-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            document.querySelector('.filter-btn.active')?.classList.remove('active');
            btn.classList.add('active');
            const filter = btn.dataset.filter;

            // Show/hide cards based on the filter
            track.querySelectorAll('.project-card').forEach(card => {
                if (filter === 'all' || card.dataset.category === filter) {
                    card.classList.remove('hidden');
                } else {
                    card.classList.add('hidden');
                }
            });
            // Reset position after filtering
            track.parentElement.scrollLeft = 0;
        });
    });

    // --- CAROUSEL NAVIGATION LOGIC ---
    const projectCarouselContainer = document.querySelector('.projects-carousel');
    const nextButton = projectCarouselContainer.querySelector('.next-btn');
    const prevButton = projectCarouselContainer.querySelector('.prev-btn');

    nextButton.addEventListener('click', () => {
        const scrollAmount = 340; // card width + gap
        track.parentElement.scrollLeft += scrollAmount;
    });

    prevButton.addEventListener('click', () => {
        const scrollAmount = 340;
        track.parentElement.scrollLeft -= scrollAmount;
    });
}

// Initialize all the interactive parts once the HTML document is fully loaded.
document.addEventListener('DOMContentLoaded', initializeCarousel);