// The hardcoded 'projects' array and the 'renderProjects' function have been REMOVED.
// The HTML for the project cards is now generated by the C# backend.

// This script now only handles the CLIENT-SIDE interactivity (filtering and navigation).

function initializeCarousel() {
    const track = document.getElementById('carouselTrack');
    if (!track) return; // Safety check to ensure the element exists

    let currentPosition = 0;

    // --- FILTERING LOGIC (UPDATED) ---
    document.querySelectorAll('.filter-btn').forEach(btn => {
        // Add the 'event' parameter to the function
        btn.addEventListener('click', (event) => {
            // PREVENT PAGE RELOAD: This is the critical fix.
            event.preventDefault();

            // Update the active button style
            document.querySelector('.filter-btn.active')?.classList.remove('active');
            btn.classList.add('active');

            const filter = btn.dataset.filter;

            // Show or hide cards based on the selected category
            track.querySelectorAll('.project-card').forEach(card => {
                if (filter === 'all' || card.dataset.category === filter) {
                    card.classList.remove('hidden');
                } else {
                    card.classList.add('hidden');
                }
            });

            // Reset the carousel position after filtering
            resetCarouselPosition();
        });
    });

    // --- CAROUSEL NAVIGATION LOGIC ---
    const projectCarouselContainer = document.querySelector('.projects-carousel');
    const nextButton = projectCarouselContainer.querySelector('.next-btn');
    const prevButton = projectCarouselContainer.querySelector('.prev-btn');

    nextButton.addEventListener('click', () => {
        const scrollAmount = 340; // card width + gap
        track.parentElement.scrollLeft += scrollAmount;
    });

    prevButton.addEventListener('click', () => {
        const scrollAmount = 340;
        track.parentElement.scrollLeft -= scrollAmount;
    });

    function resetCarouselPosition() {
        // Using scrollLeft on the parent container is more reliable
        track.parentElement.scrollLeft = 0;
        currentPosition = 0; // Also reset the position variable
    }
}

// Initialize all the interactive parts once the HTML document is fully loaded.
document.addEventListener('DOMContentLoaded', initializeCarousel);
